export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAIL = 'ACCOUNT_REGISTER_FAIL';

export const ACCOUNT_ACTIVATION_REQUEST = 'ACCOUNT_ACTIVATION_REQUEST';
export const ACCOUNT_ACTIVATION_SUCCESS = 'ACCOUNT_ACTIVATION_SUCCESS';
export const ACCOUNT_ACTIVATION_FAIL = 'ACCOUNT_ACTIVATION_FAIL';

export const ACCOUNT_RESEND_ACTIVATION_REQUEST =
  'ACCOUNT_RESEND_ACTIVATION_REQUEST';
export const ACCOUNT_RESEND_ACTIVATION_SUCCESS =
  'ACCOUNT_RESEND_ACTIVATION_SUCCESS';
export const ACCOUNT_RESEND_ACTIVATION_FAIL = 'ACCOUNT_RESEND_ACTIVATION_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const GET_ACCOUNT_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNT_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNT_FAIL = 'GET_ACCOUNT_FAIL';

export const GET_ACCOUNT_BY_ID_REQUEST = 'GET_ACCOUNT_BY_ID_REQUEST';
export const GET_ACCOUNT_BY_ID_SUCCESS = 'GET_ACCOUNT_BY_ID_SUCCESS';
export const GET_ACCOUNT_BY_ID_FAIL = 'GET_ACCOUNT_BY_ID_FAIL';

export const GET_ACCOUNT_BY_NAME_REQUEST = 'GET_ACCOUNT_BY_NAME_REQUEST';
export const GET_ACCOUNT_BY_NAME_SUCCESS = 'GET_ACCOUNT_BY_NAME_SUCCESS';
export const GET_ACCOUNT_BY_NAME_FAIL = 'GET_ACCOUNT_BY_NAME_FAIL';

export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNT_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNT_SUCCESS';
export const GET_ACCOUNTS_FAIL = 'GET_ACCOUNT_FAIL';

export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAIL = 'UPDATE_ACCOUNT_FAIL';

export const UPDATE_ACCOUNT_PASSWORD_REQUEST =
  'UPDATE_ACCOUNT_PASSWORD_REQUEST';
export const UPDATE_ACCOUNT_PASSWORD_SUCCESS =
  'UPDATE_ACCOUNT_PASSWORD_SUCCESS';
export const UPDATE_ACCOUNT_PASSWORD_FAIL = 'UPDATE_ACCOUNT_PASSWORD_FAIL';

export const UPLOAD_ACCOUNT_PROFILE_REQUEST = 'UPLOAD_ACCOUNT_PROFILE_REQUEST';
export const UPLOAD_ACCOUNT_PROFILE_SUCCESS = 'UPLOAD_ACCOUNT_PROFILE_SUCCESS';
export const UPLOAD_ACCOUNT_PROFILE_FAIL = 'UPLOAD_ACCOUNT_PROFILE_FAIL';
