export const REGISTER_TASK_COMMENT_REQUEST = 'REGISTER_TASK_COMMENT_REQUEST';
export const REGISTER_TASK_COMMENT_SUCCESS = 'REGISTER_TASK_COMMENT_SUCCESS';
export const REGISTER_TASK_COMMENT_FAIL = 'REGISTER_TASK_COMMENT_FAIL';

export const GET_TASK_COMMENT_BY_ID_REQUEST = 'GET_TASK_COMMENT_BY_ID_REQUEST';
export const GET_TASK_COMMENT_BY_ID_SUCCESS = 'GET_TASK_COMMENT_BY_ID_SUCCESS';
export const GET_TASK_COMMENT_BY_ID_FAIL = 'GET_TASK_COMMENT_BY_ID_FAIL';
