export const REGISTER_CONVERSATION_REQUEST = 'REGISTER_CONVERSATION_REQUEST';
export const REGISTER_CONVERSATION_SUCCESS = 'REGISTER_CONVERSATION_SUCCESS';
export const REGISTER_CONVERSATION_FAIL = 'REGISTER_CONVERSATION_FAIL';

export const GET_CONVERSATION_BY_ID_REQUEST = 'GET_CONVERSATION_BY_ID_REQUEST';
export const GET_CONVERSATION_BY_ID_SUCCESS = 'GET_CONVERSATION_BY_ID_SUCCESS';
export const GET_CONVERSATION_BY_ID_FAIL = 'GET_CONVERSATION_BY_ID_FAIL';
