export const REGISTER_MESSAGE_REQUEST = 'REGISTER_MESSAGE_REQUEST';
export const REGISTER_MESSAGE_SUCCESS = 'REGISTER_MESSAGE_SUCCESS';
export const REGISTER_MESSAGE_FAIL = 'REGISTER_MESSAGE_FAIL';

export const GET_MESSAGE_BY_ID_REQUEST = 'GET_MESSAGE_BY_ID_REQUEST';
export const GET_MESSAGE_BY_ID_SUCCESS = 'GET_MESSAGE_BY_ID_SUCCESS';
export const GET_MESSAGE_BY_ID_FAIL = 'GET_MESSAGE_BY_ID_FAIL';

export const GET_MESSAGES_LIST_REQUEST = 'GET_MESSAGES_LIST_REQUEST';
export const GET_MESSAGES_LIST_SUCCESS = 'GET_MESSAGES_LIST_SUCCESS';
export const GET_MESSAGES_LIST_FAIL = 'GET_MESSAGES_LIST_FAIL';

export const UPDATE_MESSAGES_SEEN_REQUEST = 'UPDATE_MESSAGES_SEEN_REQUEST';
export const UPDATE_MESSAGES_SEEN_SUCCESS = 'UPDATE_MESSAGES_SEEN_SUCCESS';
export const UPDATE_MESSAGES_SEEN_FAIL = 'UPDATE_MESSAGES_SEEN_FAIL';

export const UPLOAD_MESSAGE_ATTACHMENTS_REQUEST =
  'UPLOAD_MESSAGE_ATTACHMENTS_REQUEST';
export const UPLOAD_MESSAGE_ATTACHMENTS_SUCCESS =
  'UPLOAD_MESSAGE_ATTACHMENTS_SUCCESS';
export const UPLOAD_MESSAGE_ATTACHMENTS_FAIL =
  'UPLOAD_MESSAGE_ATTACHMENTS_FAIL';
