export const REGISTER_NOTIFICATION_REQUEST = 'REGISTER_NOTIFICATION_REQUEST';
export const REGISTER_NOTIFICATION_SUCCESS = 'REGISTER_NOTIFICATION_SUCCESS';
export const REGISTER_NOTIFICATION_FAIL = 'REGISTER_NOTIFICATION_FAIL';

export const GET_NOTIFICATION_BY_USER_ID_REQUEST =
  'GET_NOTIFICATION_BY_USER_ID_REQUEST';
export const GET_NOTIFICATION_BY_USER_ID_SUCCESS =
  'GET_NOTIFICATION_BY_USER_ID_SUCCESS';
export const GET_NOTIFICATION_BY_USER_ID_FAIL =
  'GET_NOTIFICATION_BY_USER_ID_FAIL';

export const UPDATE_TASK_NOTIF_STATUS_BY_ID_REQUEST =
  'UPDATE_TASK_NOTIF_STATUS_BY_ID_REQUEST';
export const UPDATE_TASK_NOTIF_STATUS_BY_ID_SUCCESS =
  'UPDATE_TASK_NOTIF_STATUS_BY_ID_SUCCESS';
export const UPDATE_TASK_NOTIF_STATUS_BY_ID_FAIL =
  'UPDATE_TASK_NOTIF_STATUS_BY_ID_FAIL';

export const UPDATE_TASK_NAME_LINK_REQUEST = 'UPDATE_TASK_NAME_LINK_REQUEST';
export const UPDATE_TASK_NAME_LINK_SUCCESS = 'UPDATE_TASK_NAME_LINK_SUCCESS';
export const UPDATE_TASK_NAME_LINK_FAIL = 'UPDATE_TASK_NAME_LINK_FAIL';
