export const REGISTER_PROJECT_REQUEST = 'REGISTER_PROJECT_REQUEST';
export const REGISTER_PROJECT_SUCCESS = 'REGISTER_PROJECT_SUCCESS';
export const REGISTER_PROJECT_FAIL = 'REGISTER_PROJECT_FAIL';

export const GET_PROJECT_BY_ID_REQUEST = 'GET_PROJECT_BY_ID_REQUEST';
export const GET_PROJECT_BY_ID_SUCCESS = 'GET_PROJECT_BY_ID_SUCCESS';
export const GET_PROJECT_BY_ID_FAIL = 'GET_PROJECT_BY_ID_FAIL';

export const GET_PROJECT_TASK_LIST_BY_ID_REQUEST =
  'GET_PROJECT_TASK_LIST_BY_ID_REQUEST';
export const GET_PROJECT_TASK_LIST_BY_ID_SUCCESS =
  'GET_PROJECT_TASK_LIST_BY_ID_SUCCESS';
export const GET_PROJECT_TASK_LIST_BY_ID_FAIL =
  'GET_PROJECT_TASK_LIST_BY_ID_FAIL';

export const DELETE_PROJECT_BY_ID_REQUEST = 'DELETE_PROJECT_BY_ID_REQUEST';
export const DELETE_PROJECT_BY_ID_SUCCESS = 'DELETE_PROJECT_BY_ID_SUCCESS';
export const DELETE_PROJECT_BY_ID_FAIL = 'DELETE_PROJECT_BY_ID_FAIL';

export const GET_PROJECT_LIST_REQUEST = 'GET_PROJECT_LIST_REQUEST';
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAIL = 'GET_PROJECT_LIST_FAIL';

export const UPDATE_PROJECT_BY_ID_REQUEST = 'UPDATE_PROJECT_BY_ID_REQUEST';
export const UPDATE_PROJECT_BY_ID_SUCCESS = 'UPDATE_PROJECT_BY_ID_SUCCESS';
export const UPDATE_PROJECT_BY_ID_FAIL = 'UPDATE_PROJECT_BY_ID_FAIL';
