export const REGISTER_TASK_REQUEST = 'REGISTER_TASK_REQUEST';
export const REGISTER_TASK_SUCCESS = 'REGISTER_TASK_SUCCESS';
export const REGISTER_TASK_FAIL = 'REGISTER_TASK_FAIL';

export const GET_TASK_BY_ID_REQUEST = 'GET_TASK_BY_ID_REQUEST';
export const GET_TASK_BY_ID_SUCCESS = 'GET_TASK_BY_ID_SUCCESS';
export const GET_TASK_BY_ID_FAIL = 'GET_TASK_BY_ID_FAIL';

export const GET_TASK_BY_NAME_REQUEST = 'GET_TASK_BY_NAME_REQUEST';
export const GET_TASK_BY_NAME_SUCCESS = 'GET_TASK_BY_NAME_SUCCESS';
export const GET_TASK_BY_NAME_FAIL = 'GET_TASK_BY_NAME_FAIL';

export const DELETE_TASK_BY_ID_REQUEST = 'DELETE_TASK_BY_ID_REQUEST';
export const DELETE_TASK_BY_ID_SUCCESS = 'DELETE_TASK_BY_ID_SUCCESS';
export const DELETE_TASK_BY_ID_FAIL = 'DELETE_TASK_BY_ID_FAIL';

export const UPDATE_TASK_STATUS_BY_ID_REQUEST =
  'UPDATE_TASK_STATUS_BY_ID_REQUEST';
export const UPDATE_TASK_STATUS_BY_ID_SUCCESS =
  'UPDATE_TASK_STATUS_BY_ID_SUCCESS';
export const UPDATE_TASK_STATUS_BY_ID_FAIL = 'UPDATE_TASK_STATUS_BY_ID_FAIL';

export const GET_TASK_LIST_REQUEST = 'GET_TASK_LIST_REQUEST';
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_FAIL = 'GET_TASK_LIST_FAIL';

export const UPDATE_TASK_BY_ID_REQUEST = 'UPDATE_TASK_BY_ID_REQUEST';
export const UPDATE_TASK_BY_ID_SUCCESS = 'UPDATE_TASK_BY_ID_SUCCESS';
export const UPDATE_TASK_BY_ID_FAIL = 'UPDATE_TASK_BY_ID_FAIL';

export const UPLOAD_TASK_ATTACHMENTS_REQUEST =
  'UPLOAD_TASK_ATTACHMENTS_REQUEST';
export const UPLOAD_TASK_ATTACHMENTS_SUCCESS =
  'UPLOAD_TASK_ATTACHMENTS_SUCCESS';
export const UPLOAD_TASK_ATTACHMENTS_FAIL = 'UPLOAD_TASK_ATTACHMENTS_FAIL';

export const DELETE_TASK_ATTACHMENT_REQUEST = 'DELETE_TASK_ATTACHMENT_REQUEST';
export const DELETE_TASK_ATTACHMENT_SUCCESS = 'DELETE_TASK_ATTACHMENT_SUCCESS';
export const DELETE_TASK_ATTACHMENT_FAIL = 'DELETE_TASK_ATTACHMENT_FAIL';

export const DELETE_TASK_ATTACHMENT_FILE_REQUEST =
  'DELETE_TASK_ATTACHMENT_FILE_REQUEST';
export const DELETE_TASK_ATTACHMENT_FILE_SUCCESS =
  'DELETE_TASK_ATTACHMENT_FILE_SUCCESS';
export const DELETE_TASK_ATTACHMENT_FILE_FAIL =
  'DELETE_TASK_ATTACHMENT_FILE_FAIL';
