export const REGISTER_DEPARTMENT_REQUEST = 'REGISTER_DEPARTMENT_REQUEST';
export const REGISTER_DEPARTMENT_SUCCESS = 'REGISTER_DEPARTMENT_SUCCESS';
export const REGISTER_DEPARTMENT_FAIL = 'REGISTER_DEPARTMENT_FAIL';

export const GET_DEPARTMENT_BY_ID_REQUEST = 'GET_DEPARTMENT_BY_ID_REQUEST';
export const GET_DEPARTMENT_BY_ID_SUCCESS = 'GET_DEPARTMENT_BY_ID_SUCCESS';
export const GET_DEPARTMENT_BY_ID_FAIL = 'GET_DEPARTMENT_BY_ID_FAIL';

export const GET_DEPARTMENT_LIST_REQUEST = 'GET_DEPARTMENT_LIST_REQUEST';
export const GET_DEPARTMENT_LIST_SUCCESS = 'GET_DEPARTMENTT_LIST_SUCCESS';
export const GET_DEPARTMENT_LIST_FAIL = 'GET_DEPARTMENT_LIST_FAIL';

export const REGISTER_CLIENT_REQUEST = 'REGISTER_CLIENT_REQUEST';
export const REGISTER_CLIENT_SUCCESS = 'REGISTER_CLIENT_SUCCESS';
export const REGISTER_CLIENT_FAIL = 'REGISTER_CLIENT_FAIL';

export const GET_CLIENT_LIST_REQUEST = 'GET_CLIENT_LIST_REQUEST';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAIL = 'GET_CLIENT_LIST_FAIL';

export const GET_CLIENT_BY_ID_REQUEST = 'GET_CLIENT_BY_ID_REQUEST';
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS';
export const GET_CLIENT_BY_ID_FAIL = 'GET_CLIENT_BY_ID_FAIL';

export const REGISTER_TEAM_REQUEST = 'REGISTER_TEAM_REQUEST';
export const REGISTER_TEAM_SUCCESS = 'REGISTER_TEAM_SUCCESS';
export const REGISTER_TEAM_FAIL = 'REGISTER_TEAM_FAIL';

export const GET_TEAM_BY_ID_REQUEST = 'GET_TEAM__BY_ID_REQUEST';
export const GET_TEAM_BY_ID_SUCCESS = 'GET_TEAM__BY_ID_SUCCESS';
export const GET_TEAM_BY_ID_FAIL = 'GET_TEAM__BY_ID_FAIL';

export const GET_TEAM_LIST_REQUEST = 'GET_TEAM_LIST_REQUEST';
export const GET_TEAM_LIST_SUCCESS = 'GET_TEAM_LIST_SUCCESS';
export const GET_TEAM_LIST_FAIL = 'GET_TEAM_LIST_FAIL';
